packageExtensions:
  "@aws-sdk/util-user-agent-node@^3":
    dependencies:
      aws-crt: ^1
  debug@^4:
    dependencies:
      supports-color: ^9

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
